spring.application.name=Hakamap
spring.main.log-startup-info=false
debug=false
server.address=127.0.0.1
server.port=${HAKAMAP_PORT:0}
server.tomcat.accesslog.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
logging.level.org.springframework.web=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.springframework.boot.tomcat=WARN
